import { createContext, useCallback, useContext, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { areaNavGroups, footerCompanyLinks, footerServiceLinks, mobileUtilityLinks, simpleNavLinks } from '../data/navigationCatalog'
import { serviceVerticals } from '../data/serviceCatalog'
import type { AreaNavGroup, SiteNavLink } from '../data/navigationCatalog'
import type { ServiceSlug, ServiceVertical } from '../data/serviceCatalog'

export type Language = 'es' | 'en'

type LanguageState = {
  language: Language
  setLanguage: (language: Language) => void
  toggleLanguage: () => void
  tr: (text: string) => string
}

const enText: Record<string, string> = {
  'Inicio': 'Home',
  'Seguros': 'Insurance',
  'Taxes': 'Taxes',
  'Inmigración': 'Immigration',
  'Otros Servicios': 'Other Services',
  'Nosotros': 'About',
  'Contacto': 'Contact',
  'Empresa': 'Company',
  'Proceso': 'Process',
  'Servicios': 'Services',
  'Servicios principales': 'Main Services',
  'Encuentra tu servicio': 'Find Your Service',
  'Agendar': 'Book',
  'Agendar orientación': 'Book a Consultation',
  'Agendar una llamada': 'Book a Call',
  'Agenda': 'Book',
  'WhatsApp': 'WhatsApp',
  'Llamar': 'Call',
  'Llamar ahora': 'Call Now',
  'Contactar por WhatsApp': 'Contact by WhatsApp',
  'Llamar a Christian Brokerage': 'Call Christian Brokerage',
  '¿Necesitas ayuda?': 'Need help?',
  'Escríbenos por WhatsApp': 'Message us on WhatsApp',
  'Habla con la oficina': 'Call the office',
  'Activar modo claro': 'Switch to light mode',
  'Activar modo oscuro': 'Switch to dark mode',
  'Cambiar a English': 'Switch to English',
  'Cambiar a Español': 'Switch to Spanish',
  'Ver servicios': 'View Services',
  'Ver servicios fiscales': 'View Tax Services',
  'Ver trámites': 'View Processes',
  'Ver detalle': 'View Details',
  'Ver página del área': 'View Area Page',
  'Ver área': 'View Area',
  'Orientarme': 'Guide Me',
  'Explorar': 'Explore',
  'Solicitar orientación': 'Request Guidance',
  'Cotizar cobertura': 'Quote Coverage',
  'Cotizar por WhatsApp': 'Quote on WhatsApp',
  'Consultar por WhatsApp': 'Ask on WhatsApp',
  'Preparar mis taxes': 'Prepare My Taxes',
  'Revisar documentos': 'Review Documents',
  'Reservar por WhatsApp': 'Book by WhatsApp',
  'Coordinamos la cita directamente': 'We Coordinate Your Appointment Directly',
  'Coordinamos tu cita directamente': 'We Coordinate Your Appointment Directly',
  'Calendario Christian Brokerage': 'Christian Brokerage Calendar',
  'Sábados (Enero–Abril): 10 AM - 3 PM': 'Saturdays (January-April): 10 AM - 3 PM',
  'Lun-Vie: 9 AM - 5 PM': 'Mon-Fri: 9 AM - 5 PM',
  'Todos los derechos reservados.': 'All rights reserved.',
  'Servicios administrativos y financieros sujetos a elegibilidad, regulación y documentación aplicable.': 'Administrative and financial services are subject to eligibility, regulation, and applicable documentation.',
  'Seguros, taxes e inmigración con atención local, documentos claros y acompañamiento en español.': 'Insurance, taxes, and immigration support with local service, clear documents, and bilingual guidance.',
  'Seguros, taxes e inmigración con criterio local, documentación clara y trato humano.': 'Insurance, taxes, and immigration support with local judgment, clear documentation, and human care.',
  'Washington Heights · Nueva York': 'Washington Heights · New York',
  'Atendemos a familias, conductores, dueños de negocio y contribuyentes que necesitan resolver procesos importantes sin perderse entre formularios, términos técnicos o promesas vacías.': 'We serve families, drivers, business owners, and taxpayers who need to resolve important processes without getting lost in forms, technical terms, or empty promises.',
  'Atención directa desde una oficina real: procesos de seguros, taxes e inmigración con documentos sobre la mesa.': 'Direct support from a real office: insurance, taxes, and immigration processes with documents on the table.',
  'Autoridad IRS e ITIN': 'IRS and ITIN Authority',
  'Auto, TLC, casa y negocio': 'Auto, TLC, home, and business',
  'Oficina local bilingüe': 'Local bilingual office',
  'Cotizaciones, pólizas y certificados para vida diaria y negocio.': 'Quotes, policies, and certificates for daily life and business.',
  'Declaraciones, ITIN, empresas y cartas del IRS.': 'Returns, ITINs, businesses, and IRS letters.',
  'Organización documental, traducciones y soporte administrativo.': 'Document organization, translations, and administrative support.',
  'Tres áreas, un mismo estándar: claridad documental y atención humana.': 'Three areas, one standard: clear documentation and human attention.',
  'Más de 30 años de experiencia, en el mismo local de Washington Heights.': 'More than 30 years of experience from the same Washington Heights office.',
  'Christian Brokerage es un negocio con raíces en la comunidad latina de Nueva York: atención presencial, certificaciones a la vista y un trato directo en español. Más de tres décadas en servicios financieros y administrativos, desde la misma oficina de siempre.': 'Christian Brokerage is rooted in New York’s Latino community: in-person attention, visible credentials, and direct service in Spanish and English. More than three decades in financial and administrative services from the same office.',
  'New York, NY 10032 · Washington Heights local.': 'New York, NY 10032 · Washington Heights local office.',
  'Teléfono, WhatsApp y atención en español.': 'Phone, WhatsApp, and bilingual attention.',
  'Fundador · Preparación de impuestos (EA)': 'Founder · Tax Preparation (EA)',
  'Cuenta con amplia experiencia en la preparación de impuestos y gestión administrativa, con énfasis en precisión y cumplimiento.': 'He brings deep experience in tax preparation and administrative management, with a focus on accuracy and compliance.',
  'Coordinadora de Servicios · Seguros e Inmigración': 'Service Coordinator · Insurance and Immigration',
  'Con más de 25 años de experiencia, ha desarrollado su trayectoria trabajando de forma directa con clientes, especialmente dentro de la comunidad latina de Washington Heights.': 'With more than 25 years of experience, she has built her career working directly with clients, especially within Washington Heights’ Latino community.',
  'Escuchamos el caso y pedimos solo documentos relevantes.': 'We listen to the case and request only relevant documents.',
  'Explicamos opciones, tiempos, riesgos y costos antes de avanzar.': 'We explain options, timelines, risks, and costs before moving forward.',
  'Preparamos, emitimos o presentamos con copias claras para el cliente.': 'We prepare, issue, or submit with clear copies for the client.',
  'Damos seguimiento a renovaciones, cartas, vencimientos o próximos pasos.': 'We follow up on renewals, letters, deadlines, or next steps.',
  'Empecemos por ordenar tu caso.': 'Let’s Start by Organizing Your Case.',
  'Escríbenos qué necesitas resolver y qué documentos tienes a mano. Te orientamos hacia el servicio correcto sin hacerte repetir la historia tres veces.': 'Tell us what you need to resolve and which documents you have. We guide you toward the right service without making you repeat your story three times.',
  'Te atiende Damaris Escalante': 'Damaris Escalante Will Assist You',
  'Enrolled Agent (EA) · atención bilingüe en español.': 'Enrolled Agent (EA) · bilingual attention in Spanish and English.',
  'Mientras conectamos la agenda pública, la vía más rápida es WhatsApp o una llamada a la oficina.': 'While we connect the public calendar, the fastest route is WhatsApp or a call to the office.',
  'Seguros personales y comerciales': 'Personal and Commercial Insurance',
  'Protección clara para familia, carro, casa y negocio.': 'Clear protection for family, car, home, and business.',
  'Comparamos opciones reales y te explicamos qué estás comprando antes de firmar.': 'We compare real options and explain what you are buying before you sign.',
  'Un equipo bilingüe en Nueva York que organiza coberturas, certificados y renovaciones sin vender humo ni esconder letras pequeñas.': 'A bilingual team in New York that organizes coverage, certificates, and renewals without overpromising or hiding the fine print.',
  'Agenda una llamada para cotizar seguro': 'Schedule a Call to Quote Insurance',
  'Usa el calendario si está disponible o escríbenos por WhatsApp e incluye los documentos que tengas a mano.': 'Use the calendar if available, or message us on WhatsApp and include the documents you have on hand.',
  'Cotizaciones y certificados gestionados desde una oficina local, con seguimiento humano.': 'Quotes and certificates managed from a local office, with human follow-up.',
  'Cobertura explicada': 'Coverage Explained',
  'Deducibles, límites y exclusiones en lenguaje claro.': 'Deductibles, limits, and exclusions explained in plain language.',
  'Soporte comercial': 'Business Support',
  'COI, General Liability y necesidades de contratistas.': 'COIs, General Liability, and contractor needs.',
  'Atención bilingüe': 'Bilingual Attention',
  'Acompañamiento en español durante emisión y renovación.': 'Guidance in Spanish and English during issuance and renewal.',
  'Criterio antes que precio': 'Judgment Before Price',
  'Una póliza barata puede salir cara si no protege lo que realmente importa.': 'A cheap policy can become expensive if it does not protect what really matters.',
  'El enfoque editorial para seguros es simple: menos promesa abstracta y más lectura concreta del riesgo. Revisamos uso, documentos, vencimientos y requisitos de terceros antes de recomendar.': 'Our insurance approach is simple: fewer vague promises and a more concrete reading of risk. We review usage, documents, deadlines, and third-party requirements before recommending.',
  'Auto, TLC y black car con foco en continuidad operativa.': 'Auto, TLC, and black car coverage focused on operational continuity.',
  'Negocios con certificados y cláusulas revisadas.': 'Businesses with certificates and clauses reviewed.',
  'Casa y vida con explicación de escenarios reales.': 'Home and life coverage explained through real scenarios.',
  'Taxes, ITIN y representación IRS': 'Taxes, ITIN, and IRS Representation',
  'Preparación fiscal con autoridad, orden y respaldo.': 'Tax Preparation with Authority, Order, and Support.',
  'Declaraciones, empresas, ITIN y cartas del IRS manejadas por un equipo que entiende el sistema.': 'Returns, businesses, ITINs, and IRS letters handled by a team that understands the system.',
  'Nos enfocamos en precisión, documentación y explicación. El cliente sabe qué se envía, por qué se envía y qué viene después.': 'We focus on accuracy, documentation, and explanation. Clients know what is sent, why it is sent, and what comes next.',
  'Programa una revisión fiscal': 'Schedule a Tax Review',
  'Ten a mano cartas del IRS, W-2, 1099, declaraciones previas o documentos de empresa. Si es ITIN, menciona si es solicitud nueva o renovación.': 'Have IRS letters, W-2s, 1099s, prior returns, or business documents ready. For ITIN, mention whether it is a new application or renewal.',
  'Planeación fiscal con criterio: declaraciones, ITIN y representación ante el IRS.': 'Tax planning with judgment: returns, ITINs, and IRS representation.',
  'Archivo ordenado': 'Organized File',
  'Preparación pensada para auditorías, bancos y continuidad.': 'Preparation designed for audits, banks, and continuity.',
  'Fisco sin improvisar': 'Taxes Without Improvising',
  'Los taxes no son un formulario: son una foto financiera que debe sostenerse.': 'Taxes are not just a form: they are a financial snapshot that must hold up.',
  'Por eso cuidamos consistencia entre ingresos, negocio, créditos, ITIN, cartas y planes futuros como retiro o educación. La estética acompaña esa misma disciplina: sobria, legible y confiable.': 'That is why we protect consistency across income, business, credits, ITIN, letters, and future plans like retirement or education. The design follows the same discipline: sober, legible, and trustworthy.',
  'Preparación personal y comercial.': 'Personal and business preparation.',
  'ITIN con Acceptance Agent.': 'ITIN with an Acceptance Agent.',
  'Respuesta ante avisos, auditorías y balances pendientes.': 'Response to notices, audits, and balances due.',
  'Acompañamiento documental migratorio': 'Immigration Document Support',
  'Trámites migratorios con orden, cuidado y transparencia.': 'Immigration processes with order, care, and transparency.',
  'Preparamos expedientes administrativos, traducciones y checklists con una regla: claridad desde el primer día.': 'We prepare administrative packets, translations, and checklists with one rule: clarity from day one.',
  'Cada caso necesita documentos consistentes, expectativas realistas y comunicación humana. Te ayudamos a organizar el proceso sin prometer resultados que dependen de agencias oficiales.': 'Every case needs consistent documents, realistic expectations, and human communication. We help organize the process without promising outcomes that depend on government agencies.',
  'Reserva una orientación documental': 'Book a Document Review',
  'La llamada sirve para ordenar documentos, tiempos y próximos pasos administrativos. Para asesoría legal, te indicaremos cuándo corresponde consultar a un abogado.': 'The call helps organize documents, timelines, and administrative next steps. For legal advice, we will tell you when it is appropriate to consult an attorney.',
  'Acompañamiento presencial y bilingüe para expedientes que requieren cuidado.': 'In-person bilingual support for packets that require care.',
  'Acompañamiento humano': 'Human Support',
  'Documentos, formularios y seguimiento con calma.': 'Documents, forms, and calm follow-up.',
  'Traducciones certificadas': 'Certified Translations',
  'Actas y documentos preparados para presentación.': 'Civil records and documents prepared for submission.',
  'Transparencia legal': 'Legal Transparency',
  'No somos bufete; derivamos cuando el caso requiere abogado.': 'We are not a law firm; we refer cases to an attorney when needed.',
  'Transparencia primero': 'Transparency First',
  'Organizar un expediente también es cuidar a la persona detrás del trámite.': 'Organizing a packet also means caring for the person behind the process.',
  'Inmigración necesita tacto. Reducimos ruido visual y verbal para que el visitante encuentre servicios, requisitos y límites de responsabilidad sin sentirse empujado.': 'Immigration requires tact. We reduce visual and verbal noise so visitors can find services, requirements, and responsibility limits without feeling pushed.',
  'Peticiones familiares y ajuste de estatus.': 'Family petitions and adjustment of status.',
  'Ciudadanía N-400 y N-600.': 'Citizenship N-400 and N-600.',
  'Soporte administrativo consular.': 'Consular administrative support.',
  'Christian Brokerage no es un bufete de abogados y no ofrece asesoría legal migratoria. Brindamos asistencia administrativa, traducciones, notarías y organización documental.': 'Christian Brokerage is not a law firm and does not provide immigration legal advice. We provide administrative assistance, translations, notarizations, and document organization.',
  'Notaría, divorcios, traducciones y empresas': 'Notary, Divorces, Translations, and Companies',
  'Otros servicios para tus trámites personales y de negocio.': 'Other services for your personal and business paperwork.',
  'Notaría, divorcios, traducciones certificadas y formación de compañías, con la misma claridad documental de siempre.': 'Notary, divorces, certified translations, and company formation with the same clear-document standard.',
  'Reunimos en un solo lugar los trámites que no encajan en seguros, taxes o inmigración pero que igual necesitan orden, traducciones y acompañamiento bilingüe.': 'We bring together processes that do not fit under insurance, taxes, or immigration but still need order, translations, and bilingual guidance.',
  'Agenda una orientación': 'Book a Consultation',
  'Cuéntanos qué trámite necesitas resolver y qué documentos tienes a mano. Te indicamos los próximos pasos y, cuando el caso requiere abogado, te lo decimos con claridad.': 'Tell us what process you need to resolve and which documents you have. We explain next steps and tell you clearly when a case requires an attorney.',
  'Trámites de notaría, traducciones y empresas gestionados desde una oficina local.': 'Notary, translation, and company paperwork managed from a local office.',
  'Asistencia documental': 'Document Assistance',
  'Divorcios y trámites organizados; derivamos a abogado cuando corresponde.': 'Divorce and paperwork organized; we refer to an attorney when appropriate.',
  'Formación de compañías': 'Company Formation',
  'LLC o corporación, EIN y documentos base.': 'LLC or corporation, EIN, and core documents.',
  'Todo en un solo lugar': 'Everything in One Place',
  'Trámites distintos, el mismo estándar de orden y transparencia.': 'Different processes, the same standard of order and transparency.',
  'Agrupamos notaría, divorcios, traducciones y formación de compañías para que no tengas que buscar en varios lugares. Preparamos, traducimos y organizamos; lo legal se deriva a un abogado cuando el caso lo requiere.': 'We group notary, divorce paperwork, translations, and company formation so you do not have to search in several places. We prepare, translate, and organize; legal matters are referred to an attorney when needed.',
  'Traducciones certificadas y notaría.': 'Certified translations and notary.',
  'Formación de LLC o corporación.': 'LLC or corporation formation.',
  'Christian Brokerage no es un bufete de abogados y no ofrece asesoría legal. Brindamos asistencia administrativa, traducciones, notarías y organización documental.': 'Christian Brokerage is not a law firm and does not provide legal advice. We provide administrative assistance, translations, notarizations, and document organization.',
  'Navegación principal': 'Main navigation',
  'Abrir menú': 'Open menu',
  'Cerrar menú': 'Close menu',
  'Menú de': 'Menu for',
  'servicios organizados': 'organized services',
  'Cerrar detalle': 'Close details',
  'Cerrar': 'Close',
  'Detalle del servicio': 'Service details',
  'Puntos de confianza': 'Trust points',
  'Elige el trámite o cobertura que necesitas resolver.': 'Choose the process or coverage you need to resolve.',
  'Cada tarjeta resume lo esencial. El detalle completo queda en una vista lateral para comparar sin saturar la página.': 'Each card summarizes the essentials. Full details open in a side view so you can compare without overwhelming the page.',
  'Calendario': 'Calendar',
  'Escríbenos por WhatsApp o llama a la oficina para reservar el horario más conveniente. El calendario se activará cuando el equipo conecte la agenda pública.': 'Message us on WhatsApp or call the office to reserve the most convenient time. The calendar will be activated when the team connects the public schedule.',
  'Cómo funciona': 'How It Works',
  'Requisitos': 'Requirements',
  'Consejos': 'Tips',
  'Qué es': 'What It Is',
  'Quién suele necesitarlo': 'Who Usually Needs It',
  'Paso a paso': 'Step by Step',
  'Tiempo estimado': 'Estimated Time',
  'Documentos base': 'Basic Documents',
  'Después de tu consulta podríamos solicitar información o documentos adicionales según tu caso.': 'After your consultation, we may request additional information or documents depending on your case.',
  'Incluye': 'Includes',
  'Consejo del equipo': 'Team Tip',
  'Errores comunes': 'Common Mistakes',
  'Preguntas frecuentes': 'Frequently Asked Questions',
  'Servicio:': 'Service:',
  'Hola, vengo del sitio web y necesito información.': 'Hello, I came from the website and need information.',
  'Hola, vengo del sitio web y necesito información de Christian Brokerage.': 'Hello, I came from the website and need information from Christian Brokerage.',
  'Hola, quiero agendar una orientación con Christian Brokerage.': 'Hello, I would like to book a consultation with Christian Brokerage.',
  'Hola, quiero reservar una cita con Christian Brokerage.': 'Hello, I would like to book an appointment with Christian Brokerage.',
  'Hola, necesito cotizar un seguro con Christian Brokerage.': 'Hello, I need an insurance quote from Christian Brokerage.',
  'Hola, necesito ayuda con taxes o un trámite del IRS.': 'Hello, I need help with taxes or an IRS matter.',
  'Hola, necesito orientación administrativa para un trámite migratorio.': 'Hello, I need administrative guidance for an immigration process.',
  'Hola, necesito ayuda con un trámite de notaría, divorcio, traducción o formación de compañía.': 'Hello, I need help with a notary, divorce, translation, or company formation process.',
  'Christian Brokerage | Seguros, Taxes e Inmigración en Nueva York': 'Christian Brokerage | Insurance, Taxes, and Immigration in New York',
  'Seguros Generales y Comerciales | Christian Brokerage': 'Personal and Commercial Insurance | Christian Brokerage',
  'Taxes e Impuestos Certificados | Christian Brokerage': 'Certified Taxes and IRS Support | Christian Brokerage',
  'Acompañamiento y Trámites Migratorios | Christian Brokerage': 'Immigration Process Support | Christian Brokerage',
  'Notaría, Divorcios, Traducciones y Formación de Compañías | Christian Brokerage': 'Notary, Divorces, Translations, and Company Formation | Christian Brokerage',
  'Encuentra tu servicio | Christian Brokerage': 'Find Your Service | Christian Brokerage',
  'Christian Brokerage | Seguros, Taxes e Inmigración': 'Christian Brokerage | Insurance, Taxes, and Immigration',
  'Asesoría bilingüe en seguros, taxes e inmigración desde una oficina local en Nueva York.': 'Bilingual guidance for insurance, taxes, and immigration from a local New York office.',
  'Cotiza seguro de auto, TLC, negocio, casa, vida y más con asesoría clara en español.': 'Quote auto, TLC, business, home, life insurance, and more with clear bilingual guidance.',
  'Preparación de taxes personales y comerciales, ITIN y representación ante el IRS.': 'Personal and business tax preparation, ITIN, and IRS representation.',
  'Soporte administrativo para trámites migratorios, traducciones certificadas y organización documental.': 'Administrative support for immigration processes, certified translations, and document organization.',
  'Notaría, asistencia documental en divorcios, traducciones certificadas y formación de compañías (LLC o corporación).': 'Notary, divorce document assistance, certified translations, and company formation (LLC or corporation).',
  'Cuéntanos tu situación en 3 o 4 preguntas y te recomendamos el servicio correcto, sin compromiso.': 'Tell us your situation in 3 or 4 questions and we will recommend the right service, with no obligation.',
  'Sin compromiso': 'No obligation',
  'Atención en español': 'Spanish-language attention',
  'Tus datos no se comparten': 'Your data is not shared',
  'Diagnóstico': 'Diagnostic',
  'Cuéntanos tu situación y te decimos por dónde empezar.': 'Tell us your situation and we will show you where to start.',
  'Tres o cuatro preguntas rápidas. Al final verás una recomendación clara y, si quieres, dejas tus datos. Sin compromiso.': 'Three or four quick questions. At the end you will see a clear recommendation and, if you want, you can leave your contact details. No obligation.',
  'Paso': 'Step',
  'de': 'of',
  'Paso 1': 'Step 1',
  'Paso 2': 'Step 2',
  'Paso 3': 'Step 3',
  'Paso 4': 'Step 4',
  'Atrás': 'Back',
  'Diagnóstico completado': 'Diagnostic completed',
  'Diagnóstico completado.': 'Diagnostic completed.',
  '¿Qué necesitas resolver?': 'What do you need to resolve?',
  'Bien. ¿Cuál de estos se acerca más?': 'Good. Which of these is closest?',
  'Esto es lo que recomendamos': 'This Is What We Recommend',
  '¿Para cuándo lo necesitas?': 'When do you need it?',
  'Último paso: ¿a quién contactamos?': 'Last step: who should we contact?',
  'Cuéntanos un poco más': 'Tell us a little more',
  'Elige lo que más se parezca a tu caso. Si no estás seguro, no importa: hay una opción para eso.': 'Choose what most resembles your case. If you are not sure, that is okay: there is an option for that.',
  'Quiero proteger algo': 'I want to protect something',
  'Mi carro, mi casa, mi negocio, mi familia o mi taxi/TLC.': 'My car, home, business, family, or taxi/TLC.',
  'Tengo que resolver impuestos o algo del IRS': 'I need to resolve taxes or an IRS matter',
  'Declarar taxes, sacar o renovar ITIN, o me llegó una carta del IRS.': 'File taxes, get or renew an ITIN, or respond to an IRS letter.',
  'Estoy con un trámite de inmigración': 'I am working on an immigration process',
  'Petición familiar, permiso de trabajo, residencia, ciudadanía o cita consular.': 'Family petition, work permit, residency, citizenship, or consular appointment.',
  'Necesito un documento o trámite': 'I need a document or paperwork process',
  'Notaría, traducción certificada, divorcio o abrir una compañía (LLC).': 'Notary, certified translation, divorce paperwork, or opening a company (LLC).',
  'Otros servicios': 'Other services',
  'No estoy seguro / son varias cosas': 'I am not sure / it is several things',
  'Cuéntanos el caso con tus palabras y te orientamos hacia la ruta correcta.': 'Tell us the case in your own words and we will guide you toward the right path.',
  'Te orientamos': 'We guide you',
  'Estas son las protecciones más pedidas. ¿No ves la tuya? Elige “Muéstrame todo” o pide orientación.': 'These are the most requested protections. Do not see yours? Choose “Show me everything” or ask for guidance.',
  'Estos son los trámites de impuestos más comunes. Si dudas, abajo tienes “No sé cuál es”.': 'These are the most common tax processes. If you are unsure, use “I do not know which one” below.',
  'Estos son los trámites migratorios que más acompañamos. ¿No es ninguno? Pide orientación abajo.': 'These are the immigration processes we support most often. If none fits, request guidance below.',
  'Notaría, traducciones, divorcios y compañías. Si dudas, elige “No sé cuál es”.': 'Notary, translations, divorces, and companies. If you are unsure, choose “I do not know which one.”',
  'En una o dos frases, ¿qué necesitas? (opcional) Con eso preparamos tu orientación.': 'In one or two sentences, what do you need? (optional) That helps us prepare your guidance.',
  'Ej. Me llegó una carta, tengo una renovación, o quiero abrir un negocio…': 'Example: I received a letter, I have a renewal, or I want to open a business...',
  'Ver qué recomendamos': 'See what we recommend',
  'Ver más opciones': 'See more options',
  'No sé cuál es — prefiero que me orienten': 'I do not know which one; I prefer guidance',
  'Sí, esto es — continuar': 'Yes, this is it; continue',
  'No era esto — ver otras opciones': 'This was not it; see other options',
  'Esta semana': 'This week',
  'Necesito avanzar pronto.': 'I need to move forward soon.',
  'Este mes': 'This month',
  'Estoy juntando documentos.': 'I am gathering documents.',
  'Solo orientación': 'Guidance only',
  'Quiero entender mis opciones primero.': 'I want to understand my options first.',
  '¿Cómo prefieres que te contactemos?': 'How would you prefer that we contact you?',
  'Preferencia de contacto': 'Contact preference',
  'Llamada': 'Phone call',
  'Continuar': 'Continue',
  'Solo usamos estos datos para responderte sobre tu caso. Sin spam.': 'We only use this information to respond about your case. No spam.',
  'Nombre completo': 'Full name',
  'Teléfono móvil': 'Mobile phone',
  'Email': 'Email',
  '¿Algo que debamos saber? (opcional)': 'Anything we should know? (optional)',
  'Ej. tengo una carta, una renovación o una fecha límite…': 'Example: I have a letter, a renewal, or a deadline...',
  'Tu resumen': 'Your summary',
  'Servicio': 'Service',
  'Urgencia': 'Urgency',
  'Editar': 'Edit',
  'Enviando…': 'Sending...',
  'Enviar y recibir respuesta': 'Send and receive a response',
  'Escribe tu nombre completo.': 'Enter your full name.',
  'Usa un teléfono válido de EE.UU.': 'Use a valid U.S. phone number.',
  'Usa un email válido.': 'Use a valid email.',
  'Al enviar aceptas que te contactemos sobre tu consulta. No compartimos tus datos con terceros ni te suscribimos a nada.': 'By sending, you agree that we may contact you about your inquiry. We do not share your data with third parties or subscribe you to anything.',
  '¡Listo': 'Done',
  '¡Listo!': 'Done!',
  'Recibimos tu caso.': 'We received your case.',
  'Te vamos a contactar por': 'We will contact you by',
  'para ayudarte con': 'to help you with',
  'Solemos responder el mismo día hábil, en español.': 'We usually respond the same business day, in Spanish or English.',
  '¿Prefieres adelantar? Estos son los siguientes pasos:': 'Prefer to move ahead? These are the next steps:',
  'Casi listo — terminemos por WhatsApp.': 'Almost done; let us finish by WhatsApp.',
  'Tu resumen está preparado. Para asegurarnos de no perder tu caso, toca el botón y nos llega al instante con todo el contexto.': 'Your summary is ready. To make sure we do not miss your case, tap the button and we will receive all the context instantly.',
  'Enviar resumen por WhatsApp': 'Send Summary by WhatsApp',
  'Continuar por WhatsApp': 'Continue by WhatsApp',
  '¿Prefieres hablar directo?': 'Prefer to speak directly?',
  'Orientación general': 'General Guidance',
  'Si todavía no sabes qué servicio corresponde, empezamos por ordenar el caso y ubicar la ruta correcta.': 'If you still do not know which service fits, we start by organizing the case and identifying the right path.',
  'Primera respuesta el mismo día hábil': 'First response the same business day',
  'Describe el caso, las fechas importantes y los documentos que ya tienes disponibles.': 'Describe the case, important dates, and the documents you already have available.',
  'Una buena orientación inicial evita empezar por el formulario, póliza o trámite equivocado.': 'Good initial guidance helps avoid starting with the wrong form, policy, or process.',
  'Hola, necesito orientación de Christian Brokerage sobre': 'Hello, I need guidance from Christian Brokerage about',
  'Hola, necesito orientación de Christian Brokerage.': 'Hello, I need guidance from Christian Brokerage.',
  'Hola, completé el diagnóstico en la web.': 'Hello, I completed the website diagnostic.',
  'Nombre:': 'Name:',
  'Preferencia:': 'Preference:',
  'Urgencia:': 'Urgency:',
  'Detalle:': 'Details:',
  'IRS Enrolled Agents certificados': 'Certified IRS Enrolled Agents',
  'Asistencia integral en NY y EE.UU.': 'Complete support in NY and the U.S.',
  'Respuesta humana y seguimiento': 'Human response and follow-up',
  'Asesoría 100% en tu idioma': 'Guidance 100% in your language',
  'Oficina en Washington Heights': 'Office in Washington Heights',
  'Seguros • Taxes • Inmigración': 'Insurance • Taxes • Immigration',
  'Peticiones • Notaría • Traducciones': 'Petitions • Notary • Translations',
  'Tu tranquilidad, nuestro compromiso': 'Your peace of mind, our commitment',
  'Coberturas personales, comerciales y servicios vinculados a protección.': 'Personal, commercial, and protection-related services.',
  'Vehículos': 'Vehicles',
  'Auto personal, taxi y operación TLC.': 'Personal auto, taxi, and TLC operations.',
  'Negocio y propiedad': 'Business and Property',
  'Pólizas para operar, cerrar o proteger activos.': 'Policies to operate, close contracts, or protect assets.',
  'Familia y protección': 'Family and Protection',
  'Vida, identidad y seguridad cotidiana.': 'Life, identity, and everyday security.',
  'Declaraciones': 'Returns',
  'Preparación personal y revisión del ciclo fiscal.': 'Personal preparation and tax-cycle review.',
  'Negocio': 'Business',
  'Registros y declaraciones comerciales.': 'Business records and returns.',
  'IRS e identidad fiscal': 'IRS and Tax Identity',
  'ITIN, cartas, auditorías y deudas tributarias.': 'ITIN, letters, audits, and tax debts.',
  'Planificación': 'Planning',
  'Retiro, anualidades y ahorro educativo.': 'Retirement, annuities, and education savings.',
  'Declaraciones, ITIN, empresas y representación tributaria.': 'Returns, ITIN, businesses, and tax representation.',
  'Soporte documental, traducciones y trámites administrativos.': 'Document support, translations, and administrative processes.',
  'Familia y estatus': 'Family and Status',
  'Peticiones familiares, permiso de trabajo y ajuste.': 'Family petitions, work permit, and adjustment.',
  'Ciudadanía': 'Citizenship',
  'Naturalización (N-400) y Certificado de Ciudadanía (N-600).': 'Naturalization (N-400) and Certificate of Citizenship (N-600).',
  'Consular': 'Consular',
  'Citas, formularios y paquetes para consulado.': 'Appointments, forms, and consular packets.',
  'Notaría, divorcios, traducciones y formación de compañías.': 'Notary, divorces, translations, and company formation.',
  'Documentos y notaría': 'Documents and Notary',
  'Traducciones certificadas y notarización.': 'Certified translations and notarization.',
  'Legal y familia': 'Legal and Family',
  'Asistencia documental en divorcios.': 'Document assistance for divorces.',
  'Traducciones y notaría': 'Translations and Notary',
  'Seguro de Auto Personal': 'Personal Auto Insurance',
  'Cotizamos cobertura para conductores y familias con opciones de responsabilidad civil, collision, comprehensive y asistencia en carretera.': 'We quote coverage for drivers and families with liability, collision, comprehensive, and roadside-assistance options.',
  'Licencias de EE.UU. o internacionales': 'U.S. or international licenses',
  'Planes de pago flexibles': 'Flexible payment plans',
  'Revisión de tarifa en renovaciones': 'Rate review at renewal',
  'Mismo día': 'Same day',
  'Licencia, registro o título del vehículo, dirección y póliza anterior si existe.': 'License, vehicle registration or title, address, and prior policy if available.',
  'No elijas solo el mínimo estatal. Un límite bajo puede dejar tu patrimonio expuesto si ocurre un accidente serio.': 'Do not choose only the state minimum. A low limit can leave your assets exposed if a serious accident happens.',
  'Comparación entre aseguradoras activas': 'Comparison across active carriers',
  'Tarjetas de seguro digitales': 'Digital insurance cards',
  'Acompañamiento en cambios de vehículo o conductores': 'Support for vehicle or driver changes',
  'Protección financiera para daños, responsabilidad civil y pérdidas relacionadas con el uso de un vehículo personal.': 'Financial protection for damage, liability, and losses related to personal vehicle use.',
  'Propietarios de autos particulares': 'Personal vehicle owners',
  'Familias con más de un conductor': 'Families with more than one driver',
  'Conductores nuevos en Nueva York': 'New drivers in New York',
  'Revisamos licencia, vehículo e historial.': 'We review license, vehicle, and history.',
  'Comparamos opciones de cobertura y deducible.': 'We compare coverage and deductible options.',
  'Emitimos la póliza y tarjetas de seguro.': 'We issue the policy and insurance cards.',
  'Damos seguimiento en renovación o reclamos.': 'We follow up on renewals or claims.',
  'No declarar a todos los conductores del hogar.': 'Not listing every driver in the household.',
  'Comprar por precio sin revisar deducibles y exclusiones.': 'Buying by price without reviewing deductibles and exclusions.',
  '¿Puedo cotizar con licencia internacional?': 'Can I quote with an international license?',
  'Sí. Revisamos aseguradoras que aceptan distintos perfiles de licencia y documentación.': 'Yes. We review carriers that accept different license and documentation profiles.',
  '¿Qué diferencia hay entre collision y comprehensive?': 'What is the difference between collision and comprehensive?',
  'Collision cubre choques; comprehensive cubre eventos como robo, vandalismo, ramas, granizo o daños no causados por una colisión.': 'Collision covers crashes; comprehensive covers events such as theft, vandalism, branches, hail, or damage not caused by a collision.',
  'Seguro de Taxi, TLC y Black Car': 'Taxi, TLC, and Black Car Insurance',
  'Soporte para conductores, bases y vehículos comerciales regulados por la TLC en Nueva York, incluyendo servicio black car y for-hire.': 'Support for drivers, bases, and commercial vehicles regulated by the New York TLC, including black car and for-hire service.',
  'Certificados FH-1': 'FH-1 certificates',
  'Especialidad en NY TLC y black car': 'NY TLC and black car specialty',
  'Soporte para renovaciones': 'Renewal support',
  'Mismo día según elegibilidad': 'Same day depending on eligibility',
  'Licencia TLC, información de base, registro del vehículo e historial de manejo.': 'TLC license, base information, vehicle registration, and driving history.',
  'Evita lapsos de cobertura. Un solo día sin póliza activa puede generar multas y suspensión operativa.': 'Avoid coverage lapses. A single day without an active policy can create fines and operational suspension.',
  'Carga de certificados cuando aplica': 'Certificate filing when applicable',
  'Revisión de vencimientos': 'Deadline review',
  'Orientación bilingüe para cambios de base o vehículo': 'Bilingual guidance for base or vehicle changes',
  'Seguro comercial requerido para vehículos que transportan pasajeros a cambio de una tarifa dentro de la jurisdicción TLC, incluido el servicio black car.': 'Commercial insurance required for vehicles transporting passengers for a fare within TLC jurisdiction, including black car service.',
  'Conductores de plataformas en NY': 'Platform drivers in NY',
  'Propietarios de vehículos TLC y black car': 'TLC and black car vehicle owners',
  'Pequeñas flotas de transporte': 'Small transportation fleets',
  'Validamos datos TLC y vehículo.': 'We validate TLC and vehicle information.',
  'Cotizamos pólizas comerciales elegibles.': 'We quote eligible commercial policies.',
  'Emitimos documentos y certificados.': 'We issue documents and certificates.',
  'Recordamos renovaciones críticas.': 'We remind you about critical renewals.',
  'Esperar al último día para renovar.': 'Waiting until the last day to renew.',
  'Operar con conductores no declarados correctamente.': 'Operating with drivers who are not properly listed.',
  '¿Cuánto tarda el certificado?': 'How long does the certificate take?',
  'Cuando la póliza está emitida y pagada, el certificado se procesa de forma prioritaria.': 'Once the policy is issued and paid, the certificate is processed as a priority.',
  '¿Puedo pagar mensual?': 'Can I pay monthly?',
  'En muchos casos sí. Depende de la aseguradora, historial y estructura de la póliza.': 'In many cases, yes. It depends on the carrier, history, and policy structure.',
  'Seguro de Negocio y General Liability': 'Business and General Liability Insurance',
  'Coberturas para contratistas, tiendas, restaurantes, oficinas y negocios que necesitan certificados de seguro confiables.': 'Coverage for contractors, stores, restaurants, offices, and businesses that need reliable insurance certificates.',
  'COI para contratos': 'COIs for contracts',
  'Responsabilidad civil general': 'General liability',
  'Opciones para BOP y Workers Comp': 'Options for BOP and Workers Comp',
  '24 a 48 horas': '24 to 48 hours',
  'Nombre legal, EIN, actividad, ingresos estimados, nómina y requisitos del contrato si aplica.': 'Legal name, EIN, activity, estimated revenue, payroll, and contract requirements if applicable.',
  'Si tu cliente pide Additional Insured, envía el contrato antes de cotizar para evitar correcciones de último minuto.': 'If your client asks for Additional Insured, send the contract before quoting to avoid last-minute corrections.',
  'Emisión de certificados': 'Certificate issuance',
  'Revisión de cláusulas frecuentes': 'Review of common clauses',
  'Preparación para auditorías de nómina': 'Preparation for payroll audits',
  'Cobertura que protege al negocio frente a reclamaciones por lesiones, daños a propiedad ajena y ciertos gastos de defensa.': 'Coverage that protects the business against claims for injuries, damage to third-party property, and certain defense costs.',
  'Contratistas y subcontratistas': 'Contractors and subcontractors',
  'Comercios con atención al público': 'Customer-facing businesses',
  'Negocios que presentan certificados a clientes': 'Businesses that provide certificates to clients',
  'Analizamos actividad y exposición.': 'We analyze activity and exposure.',
  'Diseñamos límites y endosos.': 'We design limits and endorsements.',
  'Emitimos póliza y certificados.': 'We issue the policy and certificates.',
  'Acompañamos renovaciones y auditorías.': 'We support renewals and audits.',
  'Declarar una actividad distinta a la real.': 'Declaring an activity different from the real one.',
  'No revisar requisitos del contrato antes de aceptar un trabajo.': 'Not reviewing contract requirements before accepting a job.',
  '¿Qué es un COI?': 'What is a COI?',
  'Es el certificado que demuestra tu cobertura ante clientes, landlords o contratistas principales.': 'It is the certificate that proves your coverage to clients, landlords, or general contractors.',
  '¿Workers Comp es lo mismo?': 'Is Workers Comp the same thing?',
  'No. Workers Comp cubre empleados; General Liability cubre reclamaciones de terceros.': 'No. Workers Comp covers employees; General Liability covers third-party claims.',
  'Casa, Apartamento y Propiedad': 'Home, Apartment, and Property',
  'Protección para propietarios, inquilinos y condominios con revisión de estructura, pertenencias y responsabilidad civil.': 'Protection for homeowners, renters, and condos with review of structure, belongings, and liability.',
  'Homeowners, renters y condo': 'Homeowners, renters, and condo',
  'Evidencia de seguro para banco o landlord': 'Evidence of insurance for bank or landlord',
  'Descuentos por paquetes': 'Bundle discounts',
  'Dirección, datos del inmueble, ocupación, valor de pertenencias y datos del banco si aplica.': 'Address, property details, occupancy, value of belongings, and bank information if applicable.',
  'El valor de reconstrucción no siempre coincide con el precio de mercado. Esa diferencia importa al momento del reclamo.': 'Reconstruction value does not always match market price. That difference matters at claim time.',
  'Revisión de deducibles': 'Deductible review',
  'Coberturas para pertenencias': 'Coverage for belongings',
  'Cartas para banco o landlord': 'Letters for bank or landlord',
  'Póliza que protege vivienda, pertenencias personales y responsabilidad civil según el tipo de ocupación.': 'A policy that protects housing, personal belongings, and liability depending on occupancy type.',
  'Propietarios de vivienda': 'Homeowners',
  'Inquilinos que quieren proteger pertenencias': 'Renters who want to protect belongings',
  'Dueños de multifamily o condo': 'Multifamily or condo owners',
  'Levantamos datos de la propiedad.': 'We gather property details.',
  'Calculamos límites recomendados.': 'We calculate recommended limits.',
  'Comparamos paquetes con auto u otras pólizas.': 'We compare bundles with auto or other policies.',
  'Emitimos evidencia para banco o arrendador.': 'We issue evidence for the bank or landlord.',
  'No asegurar bienes personales de valor.': 'Not insuring valuable personal property.',
  'Asumir que inundación siempre está incluida.': 'Assuming flood is always included.',
  '¿Renter’s insurance vale la pena?': 'Is renter’s insurance worth it?',
  'Sí. Suele ser accesible y protege pertenencias y responsabilidad personal.': 'Yes. It is usually affordable and protects belongings and personal liability.',
  '¿El banco requiere seguro?': 'Does the bank require insurance?',
  'Si tienes un préstamo sobre la propiedad, el banco normalmente exige cobertura activa.': 'If you have a loan on the property, the bank usually requires active coverage.',
  'Vida y Gastos Finales': 'Life and Final Expense',
  'Protección de vida y coberturas de gastos finales con enfoque familiar, explicadas con claridad antes de firmar.': 'Life protection and final-expense coverage with a family focus, explained clearly before you sign.',
  'Vida a término o permanente': 'Term or permanent life',
  'Cobertura de gastos finales': 'Final-expense coverage',
  'Opciones sin exámenes invasivos': 'Options without invasive exams',
  'Consulta de 30 minutos': '30-minute consultation',
  'Identificación, edad, beneficiarios deseados, miembros del hogar y necesidades de cobertura.': 'Identification, age, desired beneficiaries, household members, and coverage needs.',
  'Define beneficiarios y monto de cobertura pensando en deudas, gastos finales e ingresos que tu familia necesitaría reemplazar.': 'Define beneficiaries and coverage amount based on debts, final expenses, and income your family would need to replace.',
  'Comparación por presupuesto familiar': 'Comparison by family budget',
  'Explicación clara de beneficios y exclusiones': 'Clear explanation of benefits and exclusions',
  'Acompañamiento en la solicitud': 'Application support',
  'Soluciones de seguro de vida y de gastos finales para proteger económicamente a la familia y cubrir los costos finales.': 'Life insurance and final-expense solutions to financially protect the family and cover final costs.',
  'Padres con dependientes': 'Parents with dependents',
  'Personas con deudas o ingresos que proteger': 'People with debts or income to protect',
  'Adultos que desean planificar gastos finales': 'Adults who want to plan final expenses',
  'Identificamos necesidad y presupuesto.': 'We identify need and budget.',
  'Revisamos elegibilidad y opciones.': 'We review eligibility and options.',
  'Completamos solicitud.': 'We complete the application.',
  'Damos seguimiento a aprobación y documentos.': 'We follow up on approval and documents.',
  'Subestimar el monto de cobertura necesario.': 'Underestimating the needed coverage amount.',
  'Comprar una póliza sin entender exclusiones.': 'Buying a policy without understanding exclusions.',
  '¿Qué diferencia hay entre vida a término y permanente?': 'What is the difference between term and permanent life?',
  'La vida a término cubre un periodo definido; la permanente dura toda la vida y puede acumular valor. Revisamos cuál conviene a tu caso.': 'Term life covers a defined period; permanent life lasts a lifetime and may build value. We review what fits your case.',
  '¿Hay planes de gastos finales para mayores?': 'Are there final-expense plans for older adults?',
  'Sí, existen opciones simplificadas según edad y salud.': 'Yes, simplified options exist depending on age and health.',
  'Protección de Identidad': 'Identity Protection',
  'Monitoreo y respuestas ante robo de identidad, alertas crediticias y documentación sensible.': 'Monitoring and response for identity theft, credit alerts, and sensitive documentation.',
  'Monitoreo de señales de riesgo': 'Risk-signal monitoring',
  'Guía de pasos correctivos': 'Corrective-step guidance',
  'Protección familiar': 'Family protection',
  'Activación según plan': 'Activation according to plan',
  'Datos de identidad, correo de contacto y perfil de protección deseado.': 'Identity details, contact email, and desired protection profile.',
  'Una alerta temprana puede evitar meses de trámites con bancos, crédito y agencias.': 'An early alert can prevent months of paperwork with banks, credit bureaus, and agencies.',
  'Orientación en reportes': 'Report guidance',
  'Revisión de cuentas comprometidas': 'Review of compromised accounts',
  'Educación preventiva': 'Preventive education',
  'Servicio orientado a detectar uso indebido de datos personales y guiar acciones de mitigación.': 'A service focused on detecting misuse of personal data and guiding mitigation steps.',
  'Familias con documentos sensibles': 'Families with sensitive documents',
  'Personas que recibieron cartas de data breach': 'People who received data-breach letters',
  'Negocios que manejan información de clientes': 'Businesses handling customer information',
  'Identificamos riesgos.': 'We identify risks.',
  'Activamos monitoreo o medidas preventivas.': 'We activate monitoring or preventive measures.',
  'Guiamos reportes si hay incidente.': 'We guide reports if there is an incident.',
  'Revisamos siguientes pasos.': 'We review next steps.',
  'Ignorar avisos de filtración.': 'Ignoring breach notices.',
  'Compartir documentos por canales inseguros.': 'Sharing documents through insecure channels.',
  '¿Esto reemplaza mi banco?': 'Does this replace my bank?',
  'No. Complementa tus medidas bancarias y de crédito.': 'No. It complements your banking and credit measures.',
  '¿También sirve para familias?': 'Does it also work for families?',
  'Sí. Puede cubrir varios miembros según el plan.': 'Yes. It may cover multiple members depending on the plan.',
  'Alarmas y Seguridad': 'Alarms and Security',
  'Orientación para sistemas de alarma y seguridad que pueden apoyar la protección de casas, apartamentos y negocios.': 'Guidance for alarm and security systems that can support protection for homes, apartments, and businesses.',
  'Opciones para casa, apartamento o negocio': 'Options for home, apartment, or business',
  'Integración con descuentos': 'Integration with discounts',
  'Instalación coordinada': 'Coordinated installation',
  'Según disponibilidad': 'Depending on availability',
  'Dirección, tipo de propiedad, puntos de acceso y prioridad de monitoreo.': 'Address, property type, access points, and monitoring priority.',
  'Algunas aseguradoras reconocen descuentos por alarmas certificadas; conviene guardar evidencia de instalación.': 'Some carriers recognize discounts for certified alarms; keep installation evidence.',
  'Recomendación según riesgo': 'Risk-based recommendation',
  'Documentación para aseguradora': 'Documentation for carrier',
  'Coordinación con proveedores': 'Provider coordination',
  'Sistemas de prevención, detección y monitoreo para proteger propiedades y reducir riesgo operativo.': 'Prevention, detection, and monitoring systems to protect properties and reduce operational risk.',
  'Comercios con inventario': 'Businesses with inventory',
  'Landlords o multifamilies': 'Landlords or multifamilies',
  'Revisamos puntos vulnerables.': 'We review vulnerable points.',
  'Sugerimos tipo de sistema.': 'We suggest the type of system.',
  'Coordinamos proveedor.': 'We coordinate the provider.',
  'Documentamos instalación para pólizas.': 'We document installation for policies.',
  'Comprar equipo sin monitoreo adecuado.': 'Buying equipment without adequate monitoring.',
  'No informar a la aseguradora sobre el sistema instalado.': 'Not informing the carrier about the installed system.',
  '¿Puede bajar mi prima?': 'Can it lower my premium?',
  'En algunas pólizas sí, depende de aseguradora y certificación.': 'In some policies, yes; it depends on carrier and certification.',
  '¿Es solo para casas?': 'Is it only for homes?',
  'No. También aplica a oficinas, tiendas y propiedades comerciales.': 'No. It also applies to offices, stores, and commercial properties.',
  'Declaración Personal': 'Personal Tax Return',
  'Preparación federal y estatal para W-2, 1099, dependientes, créditos y escenarios multiestatales.': 'Federal and state preparation for W-2, 1099, dependents, credits, and multi-state scenarios.',
  'E-file seguro': 'Secure e-file',
  'Créditos familiares y educativos': 'Family and education credits',
  'Depósito directo': 'Direct deposit',
  'W-2/1099, IDs, SSN o ITIN, dependientes, cuenta bancaria y declaraciones anteriores si aplica.': 'W-2/1099, IDs, SSN or ITIN, dependents, bank account, and prior returns if applicable.',
  'Trae formularios 1098-T y gastos elegibles si hay estudios; pueden cambiar el resultado de tu reembolso.': 'Bring 1098-T forms and eligible expenses if there are education costs; they can change your refund outcome.',
  'Revisión de créditos aplicables': 'Review of applicable credits',
  'Archivo digital protegido': 'Protected digital file',
  'Explicación clara antes de enviar': 'Clear explanation before filing',
  'Declaración anual de ingresos ante IRS y estado para calcular impuestos, créditos y reembolsos.': 'Annual income return to the IRS and state to calculate taxes, credits, and refunds.',
  'Empleados W-2': 'W-2 employees',
  'Contratistas 1099': '1099 contractors',
  'Familias con dependientes': 'Families with dependents',
  'Recibimos documentos.': 'We receive documents.',
  'Revisamos ingresos y créditos.': 'We review income and credits.',
  'Preparamos federal y estatal.': 'We prepare federal and state returns.',
  'Enviamos por e-file con autorización.': 'We e-file with authorization.',
  'Omitir ingresos 1099 pequeños.': 'Omitting small 1099 income.',
  'Reclamar dependientes sin cumplir reglas del IRS.': 'Claiming dependents without meeting IRS rules.',
  '¿Cuánto tarda el reembolso?': 'How long does the refund take?',
  'El IRS suele procesar e-file con depósito directo más rápido, aunque los tiempos varían por caso.': 'The IRS usually processes e-file with direct deposit faster, although timing varies by case.',
  '¿Pueden declarar años anteriores?': 'Can you file prior years?',
  'Sí, revisamos documentos y años pendientes.': 'Yes, we review documents and pending years.',
  'Taxes Comerciales': 'Business Taxes',
  'Preparación para LLC, corporaciones, 1099, balances, gastos deducibles y planificación del ciclo fiscal.': 'Preparation for LLCs, corporations, 1099s, balances, deductible expenses, and tax-cycle planning.',
  '1120, 1120-S y 1065': '1120, 1120-S, and 1065',
  'Estimados trimestrales': 'Quarterly estimates',
  'Revisión de bookkeeping': 'Bookkeeping review',
  '3 a 5 días hábiles': '3 to 5 business days',
  'EIN, registros de ingresos/gastos, estados bancarios, nómina y declaración previa.': 'EIN, income/expense records, bank statements, payroll, and prior return.',
  'La separación entre cuentas personales y comerciales es una defensa básica para tu negocio.': 'Separating personal and business accounts is basic protection for your business.',
  'Conciliación de cierre': 'Year-end reconciliation',
  'Plan fiscal anual': 'Annual tax plan',
  'Soporte ante cartas relacionadas': 'Support for related letters',
  'Declaración fiscal de entidades comerciales para reportar ingresos, deducciones, pérdidas y obligaciones.': 'Tax return for business entities to report income, deductions, losses, and obligations.',
  'Dueños de LLC o corporación': 'LLC or corporation owners',
  'Contratistas con gastos de negocio': 'Contractors with business expenses',
  'Empresas con empleados': 'Companies with employees',
  'Organizamos registros.': 'We organize records.',
  'Clasificamos deducciones.': 'We classify deductions.',
  'Preparamos formularios.': 'We prepare forms.',
  'Planificamos pagos del siguiente ciclo.': 'We plan payments for the next cycle.',
  'Mezclar gastos personales y comerciales.': 'Mixing personal and business expenses.',
  'Presentar tarde la declaración de S-Corp o partnership.': 'Filing an S-Corp or partnership return late.',
  '¿Necesito bookkeeping mensual?': 'Do I need monthly bookkeeping?',
  'Para negocios activos, sí ayuda a reducir estrés y errores al cierre.': 'For active businesses, yes; it helps reduce stress and year-end errors.',
  '¿Qué pasa si mi negocio tuvo pérdidas?': 'What if my business had losses?',
  'Se reportan correctamente y se revisa su impacto fiscal.': 'They are reported correctly and their tax impact is reviewed.',
  'ITIN y Acceptance Agent': 'ITIN and Acceptance Agent',
  'Tramitación o renovación de ITIN con revisión documental y preparación del paquete W-7 junto a la declaración.': 'ITIN application or renewal with document review and W-7 packet preparation alongside the tax return.',
  'CAA autorizado': 'Authorized CAA',
  'Certificación en oficina': 'In-office certification',
  'Sin enviar pasaporte cuando aplica': 'No passport mailing when applicable',
  'Envío en 24 horas tras firma': 'Sent within 24 hours after signature',
  'Pasaporte vigente o documentos aceptables, declaración de taxes y datos personales.': 'Valid passport or acceptable documents, tax return, and personal information.',
  'Un Acceptance Agent puede certificar documentos elegibles para que no tengas que enviar tu pasaporte original al IRS.': 'An Acceptance Agent can certify eligible documents so you do not have to mail your original passport to the IRS.',
  'Preparación W-7': 'W-7 preparation',
  'Certificación documental': 'Document certification',
  'Seguimiento de tiempos del IRS': 'IRS timing follow-up',
  'Número de identificación tributaria para personas que necesitan declarar taxes y no califican para Seguro Social.': 'Tax identification number for people who need to file taxes and do not qualify for Social Security.',
  'Personas sin SSN que declaran taxes': 'People without SSN who file taxes',
  'Cónyuges o dependientes elegibles': 'Eligible spouses or dependents',
  'Contribuyentes que renuevan ITIN vencido': 'Taxpayers renewing an expired ITIN',
  'Revisamos identidad.': 'We review identity.',
  'Preparamos W-7 y declaración.': 'We prepare W-7 and return.',
  'Certificamos documentos elegibles.': 'We certify eligible documents.',
  'Enviamos paquete al IRS.': 'We send the packet to the IRS.',
  'Enviar pasaporte original sin necesidad.': 'Sending an original passport unnecessarily.',
  'Solicitar ITIN sin declaración cuando el caso no tiene excepción válida.': 'Applying for ITIN without a return when the case has no valid exception.',
  '¿Retienen mi pasaporte?': 'Do you keep my passport?',
  'Cuando aplica la certificación CAA, revisamos el documento en oficina y el cliente lo conserva.': 'When CAA certification applies, we review the document in office and the client keeps it.',
  '¿Cuánto tarda el IRS?': 'How long does the IRS take?',
  'El procesamiento puede tomar varias semanas, especialmente en temporada alta.': 'Processing can take several weeks, especially in high season.',
  'Cartas, Auditorías y Deudas IRS': 'IRS Letters, Audits, and Debts',
  'Representación y respuesta ante avisos, auditorías, balances pendientes, planes de pago y alivios disponibles.': 'Representation and response for notices, audits, balances due, payment plans, and available relief options.',
  'Enrolled Agents': 'Enrolled Agents',
  'Form 2848': 'Form 2848',
  'Planes de pago': 'Payment plans',
  'Respuesta inicial en 24 a 48 horas': 'Initial response in 24 to 48 hours',
  'Carta IRS o estatal, declaraciones previas, identificaciones y soportes del año cuestionado.': 'IRS or state letter, prior returns, IDs, and support documents for the questioned year.',
  'Nunca ignores una carta. Muchas tienen plazos de 30 o 90 días para responder antes de escalar.': 'Never ignore a letter. Many have 30- or 90-day deadlines before escalating.',
  'Lectura técnica del aviso': 'Technical reading of the notice',
  'Comunicación con agencias': 'Communication with agencies',
  'Estrategia de resolución': 'Resolution strategy',
  'Servicio de representación tributaria para resolver disputas, avisos, auditorías y deudas ante autoridades fiscales.': 'Tax representation service to resolve disputes, notices, audits, and debts before tax authorities.',
  'Personas con cartas CP o LT': 'People with CP or LT letters',
  'Negocios con balances pendientes': 'Businesses with balances due',
  'Contribuyentes bajo auditoría': 'Taxpayers under audit',
  'Leemos el aviso.': 'We read the notice.',
  'Solicitamos autorización si aplica.': 'We request authorization if applicable.',
  'Reunimos evidencia.': 'We gather evidence.',
  'Respondemos o negociamos la solución.': 'We respond or negotiate the solution.',
  'Responder sin entender el código del aviso.': 'Responding without understanding the notice code.',
  'No guardar recibos o pruebas del año auditado.': 'Not keeping receipts or proof for the audited year.',
  '¿Qué es un Enrolled Agent?': 'What is an Enrolled Agent?',
  'Un profesional autorizado a nivel federal para representar contribuyentes ante el IRS.': 'A federally authorized professional who represents taxpayers before the IRS.',
  '¿Pueden negociar pagos?': 'Can you negotiate payments?',
  'Sí, revisamos elegibilidad para planes, alivios y otras alternativas.': 'Yes, we review eligibility for plans, relief, and other alternatives.',
  'Retiro y Anualidades': 'Retirement and Annuities',
  'Orientación sobre estrategias de retiro, IRA, rollover y anualidades con lectura fiscal responsable.': 'Guidance on retirement strategies, IRA, rollovers, and annuities with responsible tax review.',
  'IRA tradicional o Roth': 'Traditional or Roth IRA',
  'Rollover 401(k)': '401(k) rollover',
  'Ingreso futuro planificado': 'Planned future income',
  'Consulta de 45 minutos': '45-minute consultation',
  'Edad, ingresos, cuentas existentes, objetivos y horizonte de retiro.': 'Age, income, existing accounts, goals, and retirement horizon.',
  'La diferencia entre Roth y tradicional no es solo fiscal hoy; también afecta tus retiros futuros.': 'The difference between Roth and traditional is not only today’s taxes; it also affects future withdrawals.',
  'Mapa de opciones': 'Options map',
  'Revisión de impacto fiscal': 'Tax-impact review',
  'Seguimiento de contribuciones': 'Contribution follow-up',
  'Herramientas de ahorro e ingreso futuro con reglas fiscales específicas.': 'Savings and future-income tools with specific tax rules.',
  'Trabajadores independientes': 'Self-employed workers',
  'Personas con 401(k) anterior': 'People with a prior 401(k)',
  'Familias que planifican jubilación': 'Families planning retirement',
  'Analizamos perfil.': 'We analyze the profile.',
  'Comparamos opciones.': 'We compare options.',
  'Preparamos documentos.': 'We prepare documents.',
  'Revisamos aportes y próximos pasos.': 'We review contributions and next steps.',
  'Retirar fondos temprano sin medir penalidades.': 'Withdrawing funds early without measuring penalties.',
  'Dejar cuentas antiguas sin monitoreo.': 'Leaving old accounts unmonitored.',
  '¿Esto es preparación de taxes?': 'Is this tax preparation?',
  'No solamente. Integra lectura fiscal y planificación financiera básica.': 'Not only. It combines tax review and basic financial planning.',
  '¿Puedo transferir una 401(k)?': 'Can I transfer a 401(k)?',
  'Sí, revisamos si un rollover es conveniente.': 'Yes, we review whether a rollover is appropriate.',
  'Ahorro Universitario': 'College Savings',
  'Planificación de ahorro educativo, planes 529 y documentación para familias que preparan estudios futuros.': 'Education-savings planning, 529 plans, and documentation for families preparing for future studies.',
  'Planes 529': '529 plans',
  'Metas por beneficiario': 'Goals by beneficiary',
  'Lectura de beneficios fiscales': 'Tax-benefit review',
  'Diseño en 48 horas': 'Design within 48 hours',
  'Datos del beneficiario, meta de ahorro, plazo y presupuesto familiar.': 'Beneficiary details, savings goal, timeline, and family budget.',
  'Un plan 529 puede ofrecer ventajas fiscales si se usa para gastos educativos calificados.': 'A 529 plan may offer tax advantages when used for qualified education expenses.',
  'Diseño de meta': 'Goal design',
  'Explicación de reglas de uso': 'Explanation of use rules',
  'Revisión anual de aportes': 'Annual contribution review',
  'Estrategias de ahorro destinadas a cubrir gastos educativos calificados.': 'Savings strategies designed to cover qualified education expenses.',
  'Padres y abuelos': 'Parents and grandparents',
  'Familias con hijos en edad escolar': 'Families with school-age children',
  'Personas que desean planificar estudios': 'People who want to plan education costs',
  'Definimos meta educativa.': 'We define the education goal.',
  'Revisamos opciones.': 'We review options.',
  'Preparamos apertura.': 'We prepare the opening.',
  'Programamos aportes y revisiones.': 'We schedule contributions and reviews.',
  'Usar fondos para gastos no calificados.': 'Using funds for non-qualified expenses.',
  'Empezar demasiado tarde sin meta clara.': 'Starting too late without a clear goal.',
  '¿Solo sirve para universidad?': 'Is it only for college?',
  'Puede cubrir distintos gastos educativos calificados según reglas del plan.': 'It can cover different qualified education expenses according to plan rules.',
  '¿Hay beneficio estatal?': 'Is there a state benefit?',
  'Depende del estado y del plan elegido; lo revisamos contigo.': 'It depends on the state and selected plan; we review it with you.',
  'Peticiones Familiares I-130': 'Family Petitions I-130',
  'Preparación ordenada de formularios, evidencias de relación y traducciones para procesos familiares.': 'Organized preparation of forms, relationship evidence, and translations for family processes.',
  'Pruebas de relación': 'Relationship evidence',
  'Seguimiento documental': 'Document follow-up',
  '5 a 7 días hábiles': '5 to 7 business days',
  'Actas, IDs, prueba de estatus, evidencia de relación y documentos traducidos cuando aplique.': 'Civil records, IDs, proof of status, relationship evidence, and translated documents when applicable.',
  'La calidad del paquete importa: evidencias claras, traducciones completas e índice reducen fricción.': 'Packet quality matters: clear evidence, complete translations, and an index reduce friction.',
  'Checklist por caso': 'Case-specific checklist',
  'Organización de evidencias': 'Evidence organization',
  'Copias digitales del expediente': 'Digital copies of the packet',
  'Petición usada para demostrar una relación familiar calificada ante USCIS.': 'Petition used to show a qualifying family relationship before USCIS.',
  'Ciudadanos que piden familiares inmediatos': 'Citizens petitioning immediate relatives',
  'Residentes que piden cónyuge o hijos': 'Residents petitioning a spouse or children',
  'Familias con documentos extranjeros': 'Families with foreign documents',
  'Revisamos elegibilidad documental.': 'We review document eligibility.',
  'Ordenamos pruebas civiles y relación.': 'We organize civil and relationship evidence.',
  'Armamos paquete para presentación.': 'We assemble the packet for filing.',
  'Enviar actas sin traducción certificada.': 'Sending civil records without certified translation.',
  'Presentar poca evidencia en casos matrimoniales.': 'Submitting too little evidence in marriage cases.',
  '¿Ustedes son abogados?': 'Are you attorneys?',
  'No somos bufete. Brindamos asistencia administrativa y documental; los asuntos legales se derivan a abogado cuando corresponde.': 'We are not a law firm. We provide administrative and document assistance; legal matters are referred to an attorney when appropriate.',
  '¿Pueden traducir mis actas?': 'Can you translate my civil records?',
  'Sí, ofrecemos traducciones certificadas para documentos elegibles.': 'Yes, we offer certified translations for eligible documents.',
  'Permiso de Trabajo y Ajuste': 'Work Permit and Adjustment',
  'Soporte administrativo para I-765, I-485 y paquetes de ajuste con revisión de documentos y formularios.': 'Administrative support for I-765, I-485, and adjustment packets with document and form review.',
  'Permiso de trabajo': 'Work permit',
  'Paquete I-485': 'I-485 packet',
  'Respuesta documental ante RFE': 'Document response for RFE',
  '7 días hábiles': '7 business days',
  'Pasaporte, I-94, fotos, acta, examen médico sellado si aplica y documentos del patrocinador.': 'Passport, I-94, photos, civil record, sealed medical exam if applicable, and sponsor documents.',
  'El Affidavit of Support se revisa con lupa. Ingresos, taxes y evidencia del sponsor deben estar alineados.': 'The Affidavit of Support is reviewed closely. Income, taxes, and sponsor evidence must align.',
  'Checklist por formulario': 'Checklist by form',
  'Revisión de sponsor': 'Sponsor review',
  'Preparación previa a biométricos o entrevista': 'Preparation before biometrics or interview',
  'Proceso para solicitar residencia desde dentro de EE.UU. y autorización de empleo mientras se procesa el caso.': 'Process to request residency from inside the U.S. and work authorization while the case is pending.',
  'Personas elegibles por petición familiar': 'People eligible through a family petition',
  'Solicitantes con entrada documentada': 'Applicants with documented entry',
  'Beneficiarios con patrocinador calificado': 'Beneficiaries with a qualified sponsor',
  'Validamos documentos base.': 'We validate basic documents.',
  'Organizamos soportes financieros.': 'We organize financial support documents.',
  'Armamos expediente y copias.': 'We assemble the packet and copies.',
  'Abrir el sobre médico sellado.': 'Opening the sealed medical envelope.',
  'No probar ingresos suficientes del sponsor.': 'Not proving sufficient sponsor income.',
  '¿Cuánto tarda el permiso?': 'How long does the permit take?',
  'Los tiempos cambian por categoría y oficina. Revisamos el escenario actual al preparar el caso.': 'Timelines change by category and office. We review the current scenario when preparing the case.',
  '¿Qué pasa si el sponsor no califica?': 'What if the sponsor does not qualify?',
  'Se puede evaluar un joint sponsor si cumple los requisitos.': 'A joint sponsor can be evaluated if they meet the requirements.',
  'Ciudadanía N-400 y N-600': 'Citizenship N-400 and N-600',
  'Preparación documental para naturalización (N-400) y para el Certificado de Ciudadanía (N-600) cuando los padres hacen ciudadanos a sus hijos menores de edad.': 'Document preparation for naturalization (N-400) and the Certificate of Citizenship (N-600) when parents make their minor children citizens.',
  'Naturalización N-400': 'Naturalization N-400',
  'Certificado de Ciudadanía N-600': 'Certificate of Citizenship N-600',
  'Historial de viajes y guía de civismo': 'Travel history and civics guide',
  'Green Card, ID estatal, viajes fuera de EE.UU., taxes y cambios de nombre o estado civil. Para N-600: prueba de ciudadanía del padre/madre y documentos del menor.': 'Green Card, state ID, trips outside the U.S., taxes, and name or marital-status changes. For N-600: proof of parent citizenship and minor child documents.',
  'Viajes largos y deudas fiscales sin acuerdo activo pueden afectar el análisis del caso.': 'Long trips and tax debts without an active agreement can affect case review.',
  'Auditoría documental': 'Document audit',
  'Material de estudio': 'Study material',
  'Simulación de preguntas frecuentes': 'Frequent-question simulation',
  'El N-400 es la solicitud de naturalización para residentes permanentes elegibles; el N-600 es la solicitud del Certificado de Ciudadanía para hijos menores que adquieren la ciudadanía a través de un padre o madre ciudadano.': 'The N-400 is the naturalization application for eligible permanent residents; the N-600 is the Certificate of Citizenship application for minor children who acquire citizenship through a citizen parent.',
  'Residentes permanentes de 5 años': '5-year permanent residents',
  'Residentes casados con ciudadano por 3 años': 'Residents married to a citizen for 3 years',
  'Padres que tramitan el Certificado de Ciudadanía (N-600) para sus hijos menores': 'Parents filing the Certificate of Citizenship (N-600) for minor children',
  'Revisamos presencia física y viajes.': 'We review physical presence and travel.',
  'Organizamos taxes y documentos.': 'We organize taxes and documents.',
  'Preparamos N-400 o N-600 según el caso.': 'We prepare N-400 or N-600 depending on the case.',
  'Entregamos guía de preparación.': 'We provide a preparation guide.',
  'Omitir viajes prolongados.': 'Omitting long trips.',
  'No resolver impuestos pendientes antes de aplicar.': 'Not resolving pending taxes before applying.',
  '¿Puedo aplicar a los 3 años?': 'Can I apply after 3 years?',
  'Si cumples requisitos por matrimonio con ciudadano, puede aplicar. Revisamos documentos antes.': 'If you meet requirements through marriage to a citizen, it may apply. We review documents first.',
  '¿Qué es el N-600 y cuándo aplica?': 'What is the N-600 and when does it apply?',
  'Es el Certificado de Ciudadanía. Aplica cuando un padre o madre ciudadano transmite la ciudadanía a su hijo menor de edad; te ayudamos a documentar esa relación y a preparar la solicitud.': 'It is the Certificate of Citizenship. It applies when a citizen parent transmits citizenship to a minor child; we help document that relationship and prepare the application.',
  'Soporte Consular': 'Consular Support',
  'Organización de citas, formularios y paquetes documentales para procesos consulares y trámites relacionados.': 'Organization of appointments, forms, and document packets for consular processes and related matters.',
  'Citas consulares': 'Consular appointments',
  'Formularios administrativos': 'Administrative forms',
  'Paquete para entrevista': 'Interview packet',
  '2 a 5 días hábiles': '2 to 5 business days',
  'Pasaporte, aviso o cita, caso NVC si aplica, documentos civiles y financieros.': 'Passport, notice or appointment, NVC case if applicable, civil and financial documents.',
  'Lleva al consulado copias consistentes con lo cargado digitalmente; discrepancias provocan retrasos.': 'Bring copies to the consulate that match what was uploaded digitally; discrepancies cause delays.',
  'Checklist del consulado': 'Consulate checklist',
  'Organización de carpeta': 'Folder organization',
  'Revisión de documentos cargados': 'Review of uploaded documents',
  'Asistencia administrativa para trámites ante consulados, embajadas o portales oficiales relacionados.': 'Administrative assistance for processes before consulates, embassies, or related official portals.',
  'Personas con entrevistas consulares': 'People with consular interviews',
  'Familias con procesos NVC': 'Families with NVC processes',
  'Clientes renovando pasaportes o documentos': 'Clients renewing passports or documents',
  'Revisamos requisitos.': 'We review requirements.',
  'Organizamos formularios y soportes.': 'We organize forms and supporting documents.',
  'Armamos carpeta.': 'We assemble the folder.',
  'Preparamos recordatorio de cita.': 'We prepare an appointment reminder.',
  'Llegar sin confirmación de cita.': 'Arriving without appointment confirmation.',
  'No traducir o actualizar documentos vencidos.': 'Not translating or updating expired documents.',
  '¿Gestionan la entrevista?': 'Do you manage the interview?',
  'Ayudamos con organización documental y formularios; la decisión depende de la autoridad correspondiente.': 'We help with document organization and forms; the decision depends on the corresponding authority.',
  '¿Trabajan con NVC?': 'Do you work with NVC?',
  'Sí, brindamos soporte administrativo para organizar documentos civiles y financieros.': 'Yes, we provide administrative support to organize civil and financial documents.',
  'Traducciones y Notaría': 'Translations and Notary',
  'Traducciones certificadas, affidavits y notarizaciones presenciales para trámites oficiales.': 'Certified translations, affidavits, and in-person notarizations for official processes.',
  'USCIS-friendly': 'USCIS-friendly',
  'Notaría en oficina': 'In-office notary',
  'PDF y copia física': 'PDF and physical copy',
  'Mismo día según volumen': 'Same day depending on volume',
  'Documento legible, nombre completo, destino del trámite y formato requerido.': 'Legible document, full name, destination of the process, and required format.',
  'USCIS exige certificado de traducción firmado; no basta traducir el texto en una hoja aparte.': 'USCIS requires a signed translation certificate; translating the text on a separate page is not enough.',
  'Formato claro': 'Clear format',
  'Certificación de exactitud': 'Accuracy certification',
  'Entrega digital y física': 'Digital and physical delivery',
  'Servicio de traducción certificada y validación notarial para documentos civiles o administrativos.': 'Certified translation and notarial validation service for civil or administrative documents.',
  'Personas con actas extranjeras': 'People with foreign civil records',
  'Solicitantes de inmigración': 'Immigration applicants',
  'Clientes que necesitan poderes o declaraciones': 'Clients needing powers of attorney or statements',
  'Traducimos y certificamos.': 'We translate and certify.',
  'Notarizamos si corresponde.': 'We notarize when appropriate.',
  'Entregamos copia lista para presentar.': 'We deliver a copy ready to submit.',
  'Firmar documentos antes del notario.': 'Signing documents before the notary.',
  'Enviar traducciones sin certificado.': 'Sending translations without a certificate.',
  '¿Acepta USCIS estas traducciones?': 'Does USCIS accept these translations?',
  'Preparamos traducciones certificadas con carta de exactitud, formato usado comúnmente para USCIS.': 'We prepare certified translations with an accuracy letter, a format commonly used for USCIS.',
  '¿Necesito ir a la oficina?': 'Do I need to come to the office?',
  'Para notarización presencial sí; traducciones pueden coordinarse digitalmente según documento.': 'For in-person notarization, yes; translations can be coordinated digitally depending on the document.',
  'Divorcios': 'Divorces',
  'Asistencia administrativa y documental para procesos de divorcio: preparación de formularios, traducciones y organización del expediente.': 'Administrative and document assistance for divorce processes: form preparation, translations, and file organization.',
  'Preparación de formularios': 'Form preparation',
  'Organización del expediente': 'File organization',
  'Según el caso': 'Depending on the case',
  'Identificaciones, acta de matrimonio, datos de la pareja y documentos relacionados al proceso.': 'IDs, marriage certificate, spouse information, and documents related to the process.',
  'Reúne actas y documentos consistentes desde el inicio; los errores u omisiones suelen retrasar el proceso.': 'Gather consistent civil records and documents from the beginning; errors or omissions often delay the process.',
  'Traducción y notarización cuando aplica': 'Translation and notarization when applicable',
  'Apoyo administrativo y documental para organizar y preparar la papelería de un proceso de divorcio.': 'Administrative and document support to organize and prepare the paperwork for a divorce process.',
  'Personas que inician un divorcio': 'People starting a divorce',
  'Clientes con documentos en otro idioma': 'Clients with documents in another language',
  'Familias que necesitan organizar su papelería': 'Families that need to organize paperwork',
  'Revisamos el caso y los documentos.': 'We review the case and documents.',
  'Preparamos y traducimos formularios.': 'We prepare and translate forms.',
  'Notarizamos lo que corresponda.': 'We notarize what applies.',
  'Entregamos el expediente listo para presentar.': 'We deliver the file ready to submit.',
  'Presentar formularios incompletos.': 'Submitting incomplete forms.',
  '¿Pueden traducir y notarizar los documentos?': 'Can you translate and notarize documents?',
  'Sí, ofrecemos traducciones certificadas y notarización presencial para documentos elegibles.': 'Yes, we offer certified translations and in-person notarization for eligible documents.',
  'Formación de Compañías': 'Company Formation',
  'Registro de LLC o corporación, EIN, documentos base y orientación para operar con estructura clara.': 'LLC or corporation registration, EIN, core documents, and guidance to operate with a clear structure.',
  'LLC o corporación': 'LLC or corporation',
  'EIN federal': 'Federal EIN',
  'Operating agreement': 'Operating agreement',
  '48 a 72 horas': '48 to 72 hours',
  'Nombre deseado, socios, dirección, actividad y estructura preferida.': 'Desired name, partners, address, activity, and preferred structure.',
  'Elegir entidad por moda puede salir caro. La estructura correcta depende de ingresos, riesgo y plan fiscal.': 'Choosing an entity because it is popular can be costly. The right structure depends on income, risk, and tax plan.',
  'Registro estatal': 'State registration',
  'EIN y documentos base': 'EIN and core documents',
  'Checklist inicial de cumplimiento': 'Initial compliance checklist',
  'Proceso legal-administrativo para crear una entidad separada de la persona que la opera.': 'Legal-administrative process to create an entity separate from the person operating it.',
  'Emprendedores': 'Entrepreneurs',
  'Contratistas independientes': 'Independent contractors',
  'Negocios que empiezan a contratar': 'Businesses starting to hire',
  'Definimos estructura.': 'We define structure.',
  'Verificamos nombre y datos.': 'We verify name and details.',
  'Presentamos registro.': 'We file the registration.',
  'Entregamos documentos y próximos pasos.': 'We deliver documents and next steps.',
  'Crear una entidad y no mantener registros.': 'Creating an entity and not keeping records.',
  'No entender obligaciones anuales o estatales.': 'Not understanding annual or state obligations.',
  '¿LLC o corporación?': 'LLC or corporation?',
  'Depende de actividad, socios, impuestos y objetivos. Lo revisamos en consulta.': 'It depends on activity, partners, taxes, and goals. We review it in consultation.',
  '¿El EIN llega rápido?': 'Does the EIN arrive quickly?',
  'En muchos casos se obtiene de forma rápida si la información está completa.': 'In many cases, it is obtained quickly if the information is complete.',
}

const LanguageContext = createContext<LanguageState | null>(null)

function translateDeep<T>(value: T, tr: (text: string) => string): T {
  if (typeof value === 'string') return tr(value) as T
  if (Array.isArray(value)) return value.map((item) => translateDeep(item, tr)) as T
  if (value && typeof value === 'object') {
    const next: Record<string, unknown> = {}
    for (const [key, entry] of Object.entries(value)) {
      next[key] = translateDeep(entry, tr)
    }
    return next as T
  }
  return value
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')

  const tr = useCallback(
    (text: string) => {
      if (language === 'es') return text
      return enText[text] ?? text
    },
    [language],
  )

  const toggleLanguage = useCallback(() => {
    setLanguage((current) => (current === 'es' ? 'en' : 'es'))
  }, [])

  const value = useMemo<LanguageState>(
    () => ({ language, setLanguage, toggleLanguage, tr }),
    [language, setLanguage, toggleLanguage, tr],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageState {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage debe usarse dentro de <LanguageProvider>')
  return ctx
}

export function useLocalizedServiceVerticals(): Record<ServiceSlug, ServiceVertical> {
  const { tr } = useLanguage()
  return useMemo(() => translateDeep(serviceVerticals, tr), [tr])
}

export function useLocalizedNavigation(): {
  simpleNavLinks: SiteNavLink[]
  mobileUtilityLinks: SiteNavLink[]
  areaNavGroups: AreaNavGroup[]
  footerServiceLinks: typeof footerServiceLinks
  footerCompanyLinks: typeof footerCompanyLinks
} {
  const { tr } = useLanguage()

  return useMemo(
    () => ({
      simpleNavLinks: translateDeep(simpleNavLinks, tr),
      mobileUtilityLinks: translateDeep(mobileUtilityLinks, tr),
      areaNavGroups: translateDeep(areaNavGroups, tr),
      footerServiceLinks: translateDeep(footerServiceLinks, tr),
      footerCompanyLinks: translateDeep(footerCompanyLinks, tr),
    }),
    [tr],
  )
}
